/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OcElsaWrapper {
        "serverUrl": string;
    }
}
declare global {
    interface HTMLOcElsaWrapperElement extends Components.OcElsaWrapper, HTMLStencilElement {
    }
    var HTMLOcElsaWrapperElement: {
        prototype: HTMLOcElsaWrapperElement;
        new (): HTMLOcElsaWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "oc-elsa-wrapper": HTMLOcElsaWrapperElement;
    }
}
declare namespace LocalJSX {
    interface OcElsaWrapper {
        "serverUrl"?: string;
    }
    interface IntrinsicElements {
        "oc-elsa-wrapper": OcElsaWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "oc-elsa-wrapper": LocalJSX.OcElsaWrapper & JSXBase.HTMLAttributes<HTMLOcElsaWrapperElement>;
        }
    }
}
